### ISSUE TITLE
Update to 1.0

### ISSUE THREAD

**Issue by YuanYuYuan** [ZettaScaleLabs/roscon2024_workshop#11]
- [ ] Add tag to the image. https://github.com/ZettaScaleLabs/roscon2024_workshop/blob/88fb557646b647ad7694105e80bcedb46e2932cb/docker/create_container.sh#L4.
- [ ] Add tag to the image. https://github.com/ZettaScaleLabs/roscon2024_workshop/blob/88fb557646b647ad7694105e80bcedb46e2932cb/docker/rm_image.sh#L4.

**Comment by imstevenpmwork** [comment]
This was solved by: https://github.com/ZettaScaleLabs/roscon2024_workshop/pull/13
